name: Container Scan

on: 
  push:

jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t my-snyk-image .

      - name: Run Snyk to check Docker image for vulnerabilities
        id: snyk-scan
        uses: snyk/actions/docker@v3
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: my-snyk-image
          args: --file=Dockerfile --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        if: always()   # run even if snyk step fails
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
