name: Container Scan and Push
on:
  push:
    branches:
      - main
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        id: build_image
        run: |
          IMAGE_NAME="iamahmadpk/snyk-container-demo"
          docker build -t $IMAGE_NAME .
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Snyk Monitor (for reporting to Snyk Dashboard)
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ steps.build_image.outputs.image_name }}
          args: --file=Dockerfile --exclude-base-image-vulns
          command: monitor

      - name: Run Snyk to check Docker image for vulnerabilities
        id: snyk_scan
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ steps.build_image.outputs.image_name }}
          args: --file=Dockerfile --exclude-base-image-vulns
          command: test
      - name: Push image to Docker Hub
        if: ${{ success() && steps.snyk_scan.outcome == 'success' }}
        run: docker push ${{ steps.build_image.outputs.image_name }}
